# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Enables namespacing of each library's R class
android.nonTransitiveRClass=true

# SDK auto-download (AGP 8.7+)
android.sdk.bootstrap.enabled=true
android.sdk.bootstrap.autoDownload=true
