packages:
  - 'apps/*'
  - 'packages/*'
nodeLinker: hoisted
allowBuilds:
  electron: false
  esbuild: false
  koffi: false
onlyBuiltDependencies:
  - electron
  - esbuild
  - msgpackr-extract
  - koffi
verifyDepsBeforeRun: false
